name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: admiral-project/admirald
          path: admirald

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'
          check-latest: true

      - run: go mod edit -replace github.com/admiral-project/admiral/admirald=./admirald
        name: Fix replace for CI

      - run: go mod tidy
        name: Tidy modules

      - run: test -z "$(go fmt ./...)"
        name: Check gofmt

      - run: go vet ./...
        name: go vet

      - run: go build ./...
        name: go build

      - run: go install golang.org/x/vuln/cmd/govulncheck@latest && go install github.com/securego/gosec/v2/cmd/gosec@latest
        name: Install security tools

      - run: gosec -quiet ./...
        continue-on-error: true
        name: gosec

      - run: govulncheck ./...
        continue-on-error: true
        name: govulncheck

      - run: go test ./... -count=1
        name: go test
